image: node:12

stages:
  - build
  - deploy

build:
  stage: build
  script:
   - npm install
   - npm run build
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - out/
  only:
    - master

deploy_RAM:
  stage: deploy
  dependencies:
    - build
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y)'
  script:
    - rsync -e 'ssh -p 4040' -a ./out/ ramdeploy@snekw.com:/var/www/html/sound
  environment:
    name: production
    url: https://fun.snekw.com
  only:
    - master
